name: "PyVAST Python Egg"
on:
  push:
    paths:
    - .github/workflows/release-test.yaml
    - README
  release:
    types: published
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  test:
    name: Test asset upload behavior
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    
    - name: Create Release
      if: github.event.action == 'published'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: "$GITHUB_REF"
        release_name: "$GITHUB_REF"
        body: |
          Test release delete-create assets
        draft: false
        prerelease: false

    # This step ensures that assets from previous runs are cleaned up to avoid
    # failure of the next step (asset upload)
    - name: Delete existing Release Assets
      if: github.event.action == 'published'
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ github.token }}
        tag: "$GITHUB_REF"
        fail-if-no-assets: false # don't fail if no previous assets exist
        fail-if-no-release: true # only delete assets when `tag` refers to a release
        assets: "${{ matrix.args }}-linux-static.tar.gz"

    - name: Publish to GitHub Release
      if: github.event_name == 'release' && github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: "${{ env.BUILD_DIR }}/${{ steps.create_paths.outputs.artifact_name }}"
        # The asset name is constant so we can permanently link to
        # https://github.com/tenzir/vast/releases/latest/download/vast-linux-static.tar.gz
        # for a build of the latest release.
        asset_name: "${{ matrix.args }}-linux-static.tar.gz"
        asset_content_type: application/gzip
    
    - name: Fail
      run: exit 1